"""Real-API browser workflow checks using the documented local DOM harness.

Start `python launch.py --prepare --port 8010` (without a worker) first.
The test creates SYNTHETIC cases and watches in that local demonstration DB.
It refuses to exercise writes in any other mode. No blockchain calls are made.
Requires Python Playwright and Chromium. See browser_harness.py for boundaries.
"""
from __future__ import annotations
import base64
import io
import json
import os
from pathlib import Path
import sys
import time
import zipfile
from playwright.sync_api import sync_playwright
from browser_harness import open_workspace

BASE=sys.argv[1] if len(sys.argv)>1 else 'http://127.0.0.1:8010'
OUT=Path(sys.argv[2]) if len(sys.argv)>2 else Path('ui-smoke-results.json')
results=[]

def check(name, condition):
    result={'test':name,'pass':bool(condition)}
    results.append(result)
    print(('PASS ' if condition else 'FAIL ')+name,flush=True)
    if not condition: raise AssertionError(name)

with sync_playwright() as p:
    browser=p.chromium.launch(executable_path=os.environ.get('CHROMIUM_PATH','/usr/bin/chromium'),args=['--no-sandbox'])
    page=browser.new_page(viewport={'width':1440,'height':1000})
    page.set_default_timeout(20000)
    errors=[]
    page.on('pageerror',lambda err:errors.append(str(err)))
    client=open_workspace(page,BASE)
    try:
        page.wait_for_function('state.result && state.presets.length > 0')
        page.wait_for_timeout(200)
        check('SYNTHETIC test deployment; no live writes',page.evaluate('state.config.data_mode')=='SYNTHETIC')
        check('Overview opens by default',page.locator('#page-overview').is_visible())
        counts=page.locator('.metric-value strong').all_text_contents()
        check('Overview values come from actual selected evidence',counts==['12','9','1','3'])
        check('All graph links correspond to the API graph',page.locator('#overview-graph .flow-node').count()==page.evaluate('state.result.graph.nodes.length'))
        page.locator('#theme-toggle').click()
        check('Dark theme updates its accessible control',page.locator('html').get_attribute('data-theme')=='dark' and page.locator('#theme-toggle').get_attribute('aria-label')=='Switch to light theme')
        page.locator('#theme-toggle').click()
        check('Light theme returns without replacing evidence',page.locator('html').get_attribute('data-theme')=='light' and page.evaluate('state.result.graph.nodes.length')==8)
        page.locator('[data-library-filter="SYNTHETIC"]').click()
        check('Synthetic filter returns only synthetic evidence',page.locator('.library-row').count()==1 and page.locator('.library-table .tag').inner_text()=='SYNTHETIC')
        page.locator('[data-library-filter="RECORDED_PUBLIC"]').click()
        check('Recorded filter is separate from deployment mode',page.locator('.library-row').count()==4 and page.locator('#mode').inner_text()=='SYNTHETIC')
        page.locator('#library-all').click()
        check('View all expands the actual available library',page.locator('.library-row').count()==11)
        page.locator('[data-library-filter="all"]').click()
        page.keyboard.press('Control+k')
        page.locator('#command-input').fill('monitoring')
        check('Command palette filters tools',page.locator('.command-result').count()==1)
        page.keyboard.press('Enter')
        check('Keyboard command opens the intended workflow',page.locator('#page-monitor').is_visible())
        check('Signed-out private data is not shown', 'Sign in' in page.locator('#monitor-content').inner_text())
        page.keyboard.press('?')
        check('Keyboard guide opens in a native dialog',page.locator('#help-dialog').evaluate('(e)=>e.open'))
        page.keyboard.press('Escape')
        page.evaluate("showPage('overview')")
        page.locator('#overview-graph [data-node-address]').last.click()
        page.wait_for_timeout(250)
        check('Overview node opens its exact evidence inspector','Northwind Exchange (FICTIONAL)' in page.locator('#inspector').inner_text())
        before=page.evaluate('state.graph.getScale()')
        page.locator('#zoom-in').click()
        check('Graph zoom changes the actual network camera',page.evaluate('state.graph.getScale()')>before)
        page.locator('#fit').click()
        page.locator('#fullscreen').click()
        check('Graph focus view expands without browser fullscreen access',page.locator('.graph-expanded').count()==1)
        page.keyboard.press('Escape')
        check('Escape closes graph focus view',page.locator('.graph-expanded').count()==0)
        page.locator('#tab-boundaries').focus()
        page.keyboard.press('ArrowRight')
        check('Evidence tabs support arrow-key navigation',page.locator('#tab-patterns').get_attribute('aria-selected')=='true')
        page.locator('#tab-transfers').click()
        check('Ledger preserves exact transfer amounts and qualifiers','Ordering ambiguous' in page.locator('#tab-content').inner_text())
        huge=page.evaluate("state.result.graph.edges.find(e=>e.amount_base_units.length>30).amount_display")
        check('Uint256-scale amount stays an exact string in the ledger',huge in page.locator('#tab-content').inner_text())
        page.locator('#download-json').click()
        page.wait_for_function('window.__testDownloads.length===1')
        json_blob=page.evaluate('async()=>JSON.parse(await window.__testBlobs.get(window.__testDownloads[0].url).text())')
        check('JSON download contains the exact selected evidence',json_blob['preset_id']=='synthetic-multihop' and json_blob['graph']['edges'][4]['amount_display']==huge)
        check('Demo case-export controls are disabled instead of inventing a saved case',page.locator('#export').is_disabled() and page.locator('#report').is_disabled())
        page.locator('#login-open').click()
        page.locator('#password').fill('wrong-password-for-ui-test')
        page.locator('#login-form button[type="submit"]').click()
        page.wait_for_function('!document.getElementById("login-feedback").hidden')
        check('Sign-in failure is visible inside the dialog',bool(page.locator('#login-feedback').inner_text()))
        page.locator('#password').fill('demo-password-change-me')
        page.locator('#login-form button[type="submit"]').click()
        page.wait_for_function('state.user !== null')
        check('Real local sign-in establishes an organization-scoped session',page.locator('#login-open').inner_text()=='Sign out')
        page.evaluate("showPage('overview')")
        page.locator('#quick-address').fill('TEocPZsTTRAK9x5TR66GnEbxKKU8zrNxgM')
        page.locator('#quick-trace-form button[type="submit"]').click()
        check('Wallet quick-start carries the exact address and selected network',page.locator('#address').input_value()=='TEocPZsTTRAK9x5TR66GnEbxKKU8zrNxgM' and page.locator('#network').input_value()=='tron')
        check('Quick-start does not silently submit a trace',page.evaluate('state.result===null && state.case===null'))
        page.locator('.scope-details summary').click()
        reference='UI-SMOKE-'+str(int(time.time()*1000))
        page.locator('#case-reference').fill(reference)
        page.locator('#case-title').fill('Synthetic UI verification case')
        page.locator('#seed-event').fill('tron:tx_seed_multi:0')
        page.locator('#cutoff').fill('2027-01-01T00:00')
        page.locator('#trace-submit').click()
        page.wait_for_function('state.result && state.result.id')
        check('Manual trace creates a real saved synthetic investigation',page.evaluate('state.result.integrity_verified===true'))
        check('Nearest-VASP panel uses the existing attribution summary','Northwind Exchange (FICTIONAL)' in page.locator('#nearest-vasp').inner_text())
        check('Saved-case exports become available',not page.locator('#export').is_disabled() and not page.locator('#report').is_disabled())
        saved_id=page.evaluate('state.result.id')
        case_id=page.evaluate('state.case.id')
        page.locator('#report').click()
        report_path=page.evaluate('window.__testPopups.at(-1)')
        response=client.get(report_path)
        check('Report action targets an authorized saved HTML report',response.status_code==200 and 'Northwind' in response.text)
        page.locator('#export').click()
        page.wait_for_function('window.__testDownloads.length===2',timeout=40000)
        zip_b64=page.evaluate('''async()=>{const b=await window.__testBlobs.get(window.__testDownloads[1].url).arrayBuffer();const a=new Uint8Array(b);let s='';for(let i=0;i<a.length;i+=8192)s+=String.fromCharCode(...a.subarray(i,i+8192));return btoa(s);}''')
        bundle=zipfile.ZipFile(io.BytesIO(base64.b64decode(zip_b64)))
        names=bundle.namelist()
        check('Evidence bundle contains real PDF, CSV, JSON and manifest outputs',any(n.endswith('.pdf') for n in names) and any(n.endswith('.csv') for n in names) and any('manifest' in n for n in names) and any(n.endswith('.json') for n in names))
        page.locator('#tab-boundaries').click()
        page.locator('.draft-action').first.click()
        page.locator('#draft-agency').fill('Synthetic demonstration unit')
        page.locator('#draft-officer').fill('Demo investigator')
        page.locator('#draft-summary').fill('Synthetic UI verification only; no real victim or allegation.')
        page.locator('#draft-form button.button.primary').click()
        page.wait_for_function('window.__testDownloads.length===3')
        draft=page.evaluate('async()=>JSON.parse(await window.__testBlobs.get(window.__testDownloads[2].url).text())')
        check('Request action generates a review-only draft',bool(draft.get('draft')))
        page.evaluate("showPage('cases')")
        page.wait_for_function('document.querySelectorAll(".case-row").length>0')
        check('Cases view lists the case just created',reference in page.locator('#cases-content').inner_text())
        page.locator(f'.case-runs-toggle[data-id="{case_id}"]').click()
        page.locator(f'.run-open[data-id="{saved_id}"]').click()
        page.wait_for_function('state.page==="investigate"')
        check('Saved run reopens by its actual case/run identifier',page.evaluate('state.result.id')==saved_id)
        page.evaluate("showPage('monitor')")
        page.locator('#watch-address').fill('TEocPZsTTRAK9x5TR66GnEbxKKU8zrNxgM')
        page.locator('#watch-token').fill('TQghWzGAMfcTPWzsDGWREVqKbbFMzegaGY')
        page.locator('#watch-start').fill('2026-08-01T00:00')
        page.locator('#watch-form button[type="submit"]').click()
        page.wait_for_selector('.poll-watch')
        check('Monitoring creates a watch on the selected case',page.locator('.poll-watch').count()==1)
        page.locator('.poll-watch').click()
        page.wait_for_function('document.getElementById("notice").textContent.includes("Poll ")')
        check('Watch polling reports a real source result','new alerts' in page.locator('#notice').inner_text())
        page.locator('.watch-alerts').click()
        page.wait_for_selector('#monitor-content .list-row')
        check('Watch alerts expose exact event evidence','tron:tx_seed_multi:0' in page.locator('#monitor-content').inner_text())
        page.evaluate("showPage('operations')")
        page.wait_for_selector('#ops-network option', state='attached')
        page.locator('#ops-demo').click()
        page.locator('#ops-ref').fill(reference+'-INTAKE')
        page.locator('#ops-submit').click()
        page.wait_for_selector('.ops-cancel')
        check('Complaint intake creates a durable queued job','queued' in page.locator('#ops-jobs').inner_text())
        queued_job=page.locator('.ops-cancel').first.get_attribute('data-id')
        page.locator('#ops-process').click()
        page.wait_for_selector(f'.ops-open[data-job="{queued_job}"]',timeout=40000)
        check('Queue action processes a real synthetic investigation',page.locator('.ops-open').count()>=1)
        page.evaluate("showPage('crosschain')")
        check('Live protocol checks stay disabled in synthetic mode',page.locator('#cctp-check').is_disabled())
        page.evaluate("showPage('system')")
        page.wait_for_selector('#system-content .callout')
        check('Agency connections remain explicitly unconfigured','NCRP: NOT CONFIGURED' in page.locator('#system-content').inner_text() and 'SAHYOG: NOT CONFIGURED' in page.locator('#system-content').inner_text())
        page.keyboard.press('Control+k')
        page.locator('#command-input').fill(reference)
        page.wait_for_function('document.querySelectorAll(".command-result").length>0')
        check('Command search includes only authorized cases from the API','Your case' in page.locator('#command-results').inner_text())
        page.locator('#command-input').fill('DEMO-2026-0001')
        page.locator('.command-result').filter(has_text='DEMO-2026-0001').click()
        page.wait_for_function('state.page==="investigate"')
        check('Selecting another case cannot keep the previous case evidence on screen',page.evaluate('state.result===null') and page.locator('#results').is_hidden())
        page.evaluate('async (ids)=>{renderResult(await api("/cases/"+ids.case_id+"/investigations/"+ids.saved_id));}',{'case_id':case_id,'saved_id':saved_id})
        page.locator('#login-open').click()
        page.wait_for_function('state.user===null')
        check('Logout removes private case results and cached case rows',page.evaluate('state.case===null && !state.result?.id && !document.getElementById("cases-content").textContent.trim()'))
        check('Logout erases hidden private evidence and disables saved export actions',page.locator('#inspector').text_content()=='' and page.locator('#tab-content').text_content()=='' and page.locator('#result-title').text_content()=='' and page.locator('#export').is_disabled())
        # Reopen public evidence for layout checks.
        page.locator('#explore-demo').click()
        page.wait_for_function('state.result && !state.result.id')
        for width in [1920,1440,1280,1024,768,390]:
            page.set_viewport_size({'width':width,'height':950})
            for view in ['overview','investigate','operations','cases','monitor','correlations','crosschain','decisions','system']:
                page.evaluate('(view)=>showPage(view)',view)
                page.wait_for_timeout(40)
                overflow=page.evaluate('document.documentElement.scrollWidth <= innerWidth + 1')
                check(f'{view} fits {width}px viewport without page overflow',overflow)
        check('No JavaScript runtime errors across exercised workflows',not errors)
    except Exception as exc:
        results.append({'test':'suite completion','pass':False,'detail':str(exc)})
        page.screenshot(path=str(OUT.with_suffix('.failure.png')),full_page=True)
        raise
    finally:
        OUT.write_text(json.dumps({'checks':results,'passed':sum(r['pass'] for r in results),'failed':sum(not r['pass'] for r in results),'browser_errors':errors,'scope':'local DOM harness with real SYNTHETIC FastAPI responses; browser network/cookie enforcement not tested'},indent=2))
        client.close();browser.close()
print(f'Completed {len(results)} UI checks. Results: {OUT}')
