import { useQuery } from "@tanstack/react-query";
import { Bell } from "lucide-react";
import { useState } from "react";
import { caseApi, useSession, watchApi } from "../lib/auth";
import { formatTime, humanize } from "../lib/format";
import { alertSeverity } from "../lib/status";
import { selectStyle } from "../lib/styles";
import { LoginPanel } from "../components/LoginPanel";
import { Badge, EmptyState, ErrorState, Loading, Panel, StatusBadge } from "../components/ui";

export default function AlertsPage() {
  const session = useSession();
  const [caseId, setCaseId] = useState("");
  const [watchId, setWatchId] = useState("");

  const cases = useQuery({ queryKey: ["cases"], queryFn: caseApi.list, enabled: Boolean(session.data), retry: false });
  const watches = useQuery({
    queryKey: ["watches", caseId],
    queryFn: () => watchApi.list(caseId),
    enabled: Boolean(caseId),
  });
  const alerts = useQuery({
    queryKey: ["alerts", caseId, watchId],
    queryFn: () => watchApi.alerts(caseId, watchId),
    enabled: Boolean(caseId && watchId),
  });

  if (session.isLoading) return <Loading rows={4} />;
  if (!session.data) {
    return (
      <div className="stack lg">
        <div className="page-head">
          <div>
            <h1>Alerts</h1>
            <p>Investigator alert inbox from case-scoped watches.</p>
          </div>
        </div>
        <LoginPanel intro="Alerts are generated by monitored watches and require a signed-in session. No alerts are invented where no watch produced one." />
      </div>
    );
  }

  return (
    <div className="stack lg">
      <div className="page-head">
        <div>
          <h1>Alerts</h1>
          <p>Every alert comes from a watch poll. No alert is shown without a backend source.</p>
        </div>
      </div>

      <Panel
        title="Alert inbox"
        actions={
          <div className="row" style={{ gap: 8 }}>
            <select
              value={caseId}
              onChange={(event) => {
                setCaseId(event.target.value);
                setWatchId("");
              }}
              style={selectStyle}
            >
              <option value="">Select a case…</option>
              {(cases.data ?? []).map((record) => (
                <option key={record.id} value={record.id}>
                  {record.case_reference}
                </option>
              ))}
            </select>
            <select
              value={watchId}
              onChange={(event) => setWatchId(event.target.value)}
              style={selectStyle}
              disabled={!caseId}
            >
              <option value="">Select a watch…</option>
              {(watches.data ?? []).map((watch) => (
                <option key={watch.id} value={watch.id}>
                  {watch.address.slice(0, 12)}…
                </option>
              ))}
            </select>
          </div>
        }
      >
        {!caseId || !watchId ? (
          <div className="muted">Select a case and a watch to list alerts.</div>
        ) : alerts.isLoading ? (
          <Loading rows={3} />
        ) : alerts.isError ? (
          <ErrorState message={(alerts.error as Error).message} onRetry={() => alerts.refetch()} />
        ) : (alerts.data ?? []).length === 0 ? (
          <EmptyState icon={Bell} title="No alerts for this watch">
            This watch has produced no alert in the recorded poll history.
          </EmptyState>
        ) : (
          <div className="table-wrap">
            <div className="table-scroll" style={{ maxHeight: "none" }}>
              <table className="data">
                <thead>
                  <tr>
                    <th>Severity</th>
                    <th>Type</th>
                    <th>From</th>
                    <th>To</th>
                    <th>Detected</th>
                    <th>State</th>
                  </tr>
                </thead>
                <tbody>
                  {(alerts.data ?? []).map((alert) => (
                    <tr key={alert.id}>
                      <td>
                        <StatusBadge descriptor={alertSeverity(alert.severity)} />
                      </td>
                      <td>{humanize(alert.alert_type)}</td>
                      <td className="mono">{alert.from_address?.slice(0, 12) ?? "—"}</td>
                      <td className="mono">{alert.to_address?.slice(0, 12) ?? "—"}</td>
                      <td className="muted nowrap">{formatTime(alert.first_observed_at)}</td>
                      <td>
                        <Badge tone={alert.state === "active" ? "warning" : "neutral"}>{alert.state}</Badge>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}
      </Panel>
    </div>
  );
}
