"""initial schema

Revision ID: 9902ff974344
Revises: 
Create Date: 2026-09-20 00:17:40.570380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # noqa: F401 - used by rendered JSONB variants
import app.db.base  # noqa: F401 - custom column types render as app.db.base.*
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9902ff974344'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acquisitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('request_params_hash', sa.String(length=80), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_hash', sa.String(length=80), nullable=True),
    sa.Column('status', sa.Enum('pending', 'succeeded', 'failed', 'partial', name='acquisition_status'), nullable=False),
    sa.Column('coverage_status', sa.Enum('complete_within_scope', 'partial', 'unknown', 'failed', name='coverage_status'), nullable=False),
    sa.Column('error_class', sa.String(length=80), nullable=True),
    sa.Column('analysis_cutoff', sa.DateTime(timezone=True), nullable=False),
    sa.Column('parser_version', sa.String(length=20), nullable=False),
    sa.Column('data_mode', sa.Enum('LIVE', 'RECORDED_PUBLIC', 'SYNTHETIC', name='data_mode'), nullable=False),
    sa.Column('capture_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attribution_evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=80), nullable=False),
    sa.Column('source_reference', sa.Text(), nullable=False),
    sa.Column('retrieval_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('document_hash', sa.String(length=128), nullable=True),
    sa.Column('methodology', sa.Text(), nullable=False),
    sa.Column('reviewer', sa.String(length=200), nullable=True),
    sa.Column('reuse_terms', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('entity_type', sa.Enum('exchange', 'custodial_service', 'payment_processor', 'mixer', 'bridge', 'merchant', 'gambling', 'sanctioned_entity', 'unknown', name='entity_type'), nullable=False),
    sa.Column('jurisdiction', sa.String(length=80), nullable=True),
    sa.Column('parent_entity_id', sa.Uuid(), nullable=True),
    sa.Column('data_mode', sa.Enum('LIVE', 'RECORDED_PUBLIC', 'SYNTHETIC', name='data_mode'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_entity_id'], ['entities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('networks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('family', sa.Enum('account', 'utxo', name='network_family'), nullable=False),
    sa.Column('chain_id', sa.BigInteger(), nullable=True),
    sa.Column('caip2', sa.String(length=80), nullable=True),
    sa.Column('native_asset_symbol', sa.String(length=20), nullable=False),
    sa.Column('is_supported', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('addresses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('network_id', sa.Uuid(), nullable=False),
    sa.Column('canonical_address', sa.String(length=128), nullable=False),
    sa.Column('original_input', sa.String(length=128), nullable=False),
    sa.Column('address_format', sa.String(length=40), nullable=False),
    sa.Column('first_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_mode', sa.Enum('LIVE', 'RECORDED_PUBLIC', 'SYNTHETIC', name='data_mode'), nullable=False),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('network_id', 'canonical_address', name='uq_address_identity')
    )
    op.create_table('assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('network_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('native', 'token', name='asset_kind'), nullable=False),
    sa.Column('token_contract', sa.String(length=128), nullable=True),
    sa.Column('decimals', sa.Integer(), nullable=False),
    sa.Column('display_symbol', sa.String(length=40), nullable=False),
    sa.Column('issuer_reference', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_supported', sa.Boolean(), nullable=False),
    sa.Column('data_mode', sa.Enum('LIVE', 'RECORDED_PUBLIC', 'SYNTHETIC', name='data_mode'), nullable=False),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('network_id', 'kind', 'token_contract', name='uq_asset_identity')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('object_type', sa.String(length=80), nullable=True),
    sa.Column('object_id', sa.String(length=80), nullable=True),
    sa.Column('request_id', sa.String(length=80), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blocks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('network_id', sa.Uuid(), nullable=False),
    sa.Column('height', sa.BigInteger(), nullable=False),
    sa.Column('block_hash', sa.String(length=128), nullable=False),
    sa.Column('parent_hash', sa.String(length=128), nullable=True),
    sa.Column('block_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_canonical', sa.Boolean(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('data_mode', sa.Enum('LIVE', 'RECORDED_PUBLIC', 'SYNTHETIC', name='data_mode'), nullable=False),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('network_id', 'block_hash', name='uq_block_identity')
    )
    op.create_table('cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('case_reference', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('data_mode', sa.Enum('LIVE', 'RECORDED_PUBLIC', 'SYNTHETIC', name='data_mode'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'case_reference', name='uq_case_reference')
    )
    op.create_table('memberships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organization_id', name='uq_membership')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('network_id', sa.Uuid(), nullable=False),
    sa.Column('tx_hash', sa.String(length=128), nullable=False),
    sa.Column('execution_status', sa.Enum('success', 'failed', 'reverted', 'unknown', name='execution_status'), nullable=False),
    sa.Column('fee_base_units', app.db.base.BaseUnits(precision=78, scale=0), nullable=True),
    sa.Column('raw_reference', sa.Text(), nullable=True),
    sa.Column('data_mode', sa.Enum('LIVE', 'RECORDED_PUBLIC', 'SYNTHETIC', name='data_mode'), nullable=False),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('network_id', 'tx_hash', name='uq_transaction_identity')
    )
    op.create_table('exports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('bundle_version', sa.String(length=40), nullable=False),
    sa.Column('manifest_hash', sa.String(length=128), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('label_assertions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('address_id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('assertion_type', sa.Enum('service_control', 'deposit_candidate', 'complaint_allegation', 'public_abuse_report', 'sanctions_tag', name='assertion_type'), nullable=False),
    sa.Column('address_role', sa.Enum('deposit', 'hot_wallet', 'cold_reserve', 'withdrawal', 'settlement', 'unknown', name='address_role'), nullable=False),
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.Column('review_state', sa.Enum('unreviewed', 'accepted', 'rejected', 'quarantined', 'conflicted', name='review_state'), nullable=False),
    sa.Column('attribution_status', sa.Enum('supported', 'inferred', 'candidate', 'conflicted', 'unresolved', 'unsupported', name='attribution_status'), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('label_set_version', sa.String(length=40), nullable=False),
    sa.Column('data_mode', sa.Enum('LIVE', 'RECORDED_PUBLIC', 'SYNTHETIC', name='data_mode'), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['evidence_id'], ['attribution_evidence.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_inclusions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('block_id', sa.Uuid(), nullable=False),
    sa.Column('index_in_block', sa.Integer(), nullable=True),
    sa.Column('is_canonical', sa.Boolean(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id', 'block_id', name='uq_inclusion')
    )
    op.create_table('transfer_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('network_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('event_reference', sa.String(length=200), nullable=False),
    sa.Column('event_kind', sa.Enum('transfer', 'approval', 'internal_transfer', 'contract_call', 'unknown', name='event_kind'), nullable=False),
    sa.Column('from_address_id', sa.Uuid(), nullable=True),
    sa.Column('to_address_id', sa.Uuid(), nullable=True),
    sa.Column('amount_base_units', app.db.base.BaseUnits(precision=78, scale=0), nullable=False),
    sa.Column('execution_status', sa.Enum('success', 'failed', 'reverted', 'unknown', name='execution_status'), nullable=False),
    sa.Column('confirmation_state', sa.Enum('provisional', 'confirmed', 'removed', 'unknown', name='confirmation_state'), nullable=False),
    sa.Column('block_id', sa.Uuid(), nullable=True),
    sa.Column('block_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('chain_sequence', sa.String(length=80), nullable=True),
    sa.Column('ordering_ambiguous', sa.Boolean(), nullable=False),
    sa.Column('is_zero_value', sa.Boolean(), nullable=False),
    sa.Column('parser_version', sa.String(length=20), nullable=False),
    sa.Column('data_mode', sa.Enum('LIVE', 'RECORDED_PUBLIC', 'SYNTHETIC', name='data_mode'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_address_id'], ['addresses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_address_id'], ['addresses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('network_id', 'event_reference', name='uq_event_identity')
    )
    op.create_index('ix_transfer_events_from', 'transfer_events', ['from_address_id', 'chain_sequence'], unique=False)
    op.create_index('ix_transfer_events_to', 'transfer_events', ['to_address_id', 'chain_sequence'], unique=False)
    op.create_table('watches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('network_id', sa.Uuid(), nullable=False),
    sa.Column('address_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('cursor', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('acquisition_events',
    sa.Column('acquisition_id', sa.Uuid(), nullable=False),
    sa.Column('transfer_event_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['acquisition_id'], ['acquisitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transfer_event_id'], ['transfer_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('acquisition_id', 'transfer_event_id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('watch_id', sa.Uuid(), nullable=False),
    sa.Column('rule_key', sa.String(length=80), nullable=False),
    sa.Column('rule_version', sa.String(length=40), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['watch_id'], ['watches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watch_id', 'dedupe_key', name='uq_alert_dedupe')
    )
    op.create_table('case_seeds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.Enum('incident', 'address_discovery', name='seed_mode'), nullable=False),
    sa.Column('network_id', sa.Uuid(), nullable=False),
    sa.Column('address_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=True),
    sa.Column('transfer_event_id', sa.Uuid(), nullable=True),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('amount_base_units', app.db.base.BaseUnits(precision=78, scale=0), nullable=True),
    sa.Column('incident_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transfer_event_id'], ['transfer_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trace_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('case_seed_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'partial', 'completed', 'failed', 'cancelled', name='trace_run_status'), nullable=False),
    sa.Column('engine_version', sa.String(length=40), nullable=False),
    sa.Column('label_set_version', sa.String(length=40), nullable=False),
    sa.Column('analysis_cutoff', sa.DateTime(timezone=True), nullable=False),
    sa.Column('budgets', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('input_hash', sa.String(length=80), nullable=False),
    sa.Column('coverage_status', sa.Enum('complete_within_scope', 'partial', 'unknown', 'failed', name='coverage_status'), nullable=False),
    sa.Column('data_mode', sa.Enum('LIVE', 'RECORDED_PUBLIC', 'SYNTHETIC', name='data_mode'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_seed_id'], ['case_seeds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trace_states',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trace_run_id', sa.Uuid(), nullable=False),
    sa.Column('parent_state_id', sa.Uuid(), nullable=True),
    sa.Column('network_id', sa.Uuid(), nullable=False),
    sa.Column('address_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('arrival_event_id', sa.Uuid(), nullable=True),
    sa.Column('hop_depth', sa.Integer(), nullable=False),
    sa.Column('branch_path', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('boundary_reason', sa.Enum('service_boundary', 'hop_limit', 'event_limit', 'time_limit', 'api_budget', 'unsupported_asset_change', 'bridge', 'privacy_mechanism', 'opaque_contract', 'no_outgoing_activity', 'ambiguous_ordering', 'cancelled', 'provider_failure', name='boundary_reason'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['arrival_event_id'], ['transfer_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_state_id'], ['trace_states.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trace_run_id'], ['trace_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('findings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trace_run_id', sa.Uuid(), nullable=False),
    sa.Column('trace_state_id', sa.Uuid(), nullable=True),
    sa.Column('finding_type', sa.String(length=60), nullable=False),
    sa.Column('attribution_status', sa.Enum('supported', 'inferred', 'candidate', 'conflicted', 'unresolved', 'unsupported', name='attribution_status'), nullable=False),
    sa.Column('coverage_status', sa.Enum('complete_within_scope', 'partial', 'unknown', 'failed', name='coverage_status'), nullable=False),
    sa.Column('case_flow_linkage', sa.Enum('established', 'partial', 'not_established', 'ambiguous', name='case_flow_linkage'), nullable=False),
    sa.Column('boundary_reason', sa.Enum('service_boundary', 'hop_limit', 'event_limit', 'time_limit', 'api_budget', 'unsupported_asset_change', 'bridge', 'privacy_mechanism', 'opaque_contract', 'no_outgoing_activity', 'ambiguous_ordering', 'cancelled', 'provider_failure', name='boundary_reason'), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('address_id', sa.Uuid(), nullable=True),
    sa.Column('observed_amount_base_units', app.db.base.BaseUnits(precision=78, scale=0), nullable=True),
    sa.Column('case_amount_basis', sa.Enum('allocation_unknown', 'direct_seed_transfer', 'bounded_estimate', name='case_amount_basis'), nullable=False),
    sa.Column('case_amount_lower_base_units', app.db.base.BaseUnits(precision=78, scale=0), nullable=True),
    sa.Column('case_amount_upper_base_units', app.db.base.BaseUnits(precision=78, scale=0), nullable=True),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trace_run_id'], ['trace_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trace_state_id'], ['trace_states.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('findings')
    op.drop_table('trace_states')
    op.drop_table('trace_runs')
    op.drop_table('case_seeds')
    op.drop_table('alerts')
    op.drop_table('acquisition_events')
    op.drop_table('watches')
    op.drop_index('ix_transfer_events_to', table_name='transfer_events')
    op.drop_index('ix_transfer_events_from', table_name='transfer_events')
    op.drop_table('transfer_events')
    op.drop_table('transaction_inclusions')
    op.drop_table('label_assertions')
    op.drop_table('exports')
    op.drop_table('transactions')
    op.drop_table('memberships')
    op.drop_table('cases')
    op.drop_table('blocks')
    op.drop_table('audit_events')
    op.drop_table('assets')
    op.drop_table('addresses')
    op.drop_table('users')
    op.drop_table('organizations')
    op.drop_table('networks')
    op.drop_table('entities')
    op.drop_table('attribution_evidence')
    op.drop_table('acquisitions')
    # ### end Alembic commands ###
